### ISSUE TITLE
The link `https://pictureweb.s3-us-west-2.amazonaws.com/human_accuracy.pickle` is invalid now.

### ISSUE THREAD

**Issue by wkcn** [modestyachts/evaluating_machine_accuracy_on_imagenet#1]
Hi there, thanks for your great work!

I found the link `https://pictureweb.s3-us-west-2.amazonaws.com/human_accuracy.pickle` in [human_accuracy_streamlit.py](https://github.com/modestyachts/evaluating_machine_accuracy_on_imagenet/blob/master/human_accuracy_streamlit.py#L68) is invalid now.

I have fixed it in the PR #2 .

## Reproduce Procedure
`python human_accuracy_streamlit.py`

## Error
```
Traceback (most recent call last):
  File "human_accuracy_streamlit.py", line 122, in <module>
    h_a = load_data()
  File "human_accuracy_streamlit.py", line 68, in load_data
    data_bytes = urllib.request.urlopen("https://pictureweb.s3-us-west-2.amazonaws.com/human_accuracy.pickle").read()
  File "/home/wkcn/miniconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/wkcn/miniconda3/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/wkcn/miniconda3/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/wkcn/miniconda3/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/wkcn/miniconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/wkcn/miniconda3/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by wkcn** [comment]
Close it since the PR #2 has been merged. : )
